Refactor tests and add "add facility" test
tonari/backend pull request #1
Opened 2019-10-16 12:38 UTC by schra

2019-10-16 18:40 UTC, aticu requested changes

2019-10-16 18:40 UTC, aticu commented on tests/framework.bash
> +  local now_
I think something like `startTime` would be better than `now_` here.

2019-10-16 18:40 UTC, aticu commented on tests/framework.bash
> +  await 5000 curl -sS --max-time 1 --connect-timeout 1 "http://$TONARI_IP:8000/facilities/by-radius/1/1/1"
I think I'd prefer the request `/facilities/by-tile/0/0/0` here. The current request requests facilities at an arbitrary location, while this one would request all facilities.

Or we could comment that it is just an arbitrarily chosen request.

If we do neither of these things I fear that a reader of this code may try to find the significance of this request.

2019-10-16 18:40 UTC, aticu commented on tests/sigint-stops-docker-container.bats
> +  if ! container-running "$TONARI"; then
I might be mistaken here, but isn't this what's already being checked by `await-http` in `setup()`?

2019-10-17 09:00 UTC, schra commented on tests/framework.bash
> +  await 5000 curl -sS --max-time 1 --connect-timeout 1 "http://$TONARI_IP:8000/facilities/by-radius/1/1/1"
Indeed this makes more sense.

2019-10-17 09:00 UTC, schra commented on tests/sigint-stops-docker-container.bats
> +  if ! container-running "$TONARI"; then
Oh yeah it is.

2019-10-17 09:50 UTC, aticu approved these changes

2019-10-17 18:01 UTC, merged