Add more tests and update test framework
tonari/backend pull request #2
Opened 2019-11-03 21:57 UTC by aticu

2019-11-10 16:11 UTC, schra requested changes
Nice :) Looks good so far, there are just a couple of minor issues

2019-11-10 16:11 UTC, schra commented on tests/framework.bash
> +extract-field() {
`jq` can already do this by itself. Remove this function and replace calls to it with `echo "$jsonObject" | jq -r "$jqQuery"`

2019-11-10 16:11 UTC, schra commented on tests/add-facility.bats
> +  field-equals "$result" .result "success"
I don't really care about this, so I'll accept this either way but could you explain why you think that `"foobar"` is more readable than `foobar`?

2019-11-10 16:11 UTC, schra commented on tests/radius-search.bats
> +  field-equals "$result" .result success
Here you didn't used quotes like you did in the first commit where you added quotes in these cases. Did you do that on purpose?

2019-11-10 16:11 UTC, schra commented on tests/by-id.bats
> +  local originalId=$(extract-field "$result" .features[0].properties.originalId "string")
We should make the usage of `local` consistent. So either delete it everywhere or (I'd propose this solution) to add it also for e.g. `request` and `result` (in this test and the other tests)

2019-11-10 16:11 UTC, schra commented on tests/image-upload.bats
> +  head -c "$((3*width*height))" /dev/urandom | convert -depth 8 -size "$width"x"$height" RGB:- "$tmpdir/image.jpg"
Nice :D

2019-11-10 16:11 UTC, schra commented on tests/by-id.bats
> +    "createNewFacility": true,
You are creating a new facility 12 times in total. We'd save a lot of lines if you create a Bash function for this (which makes this operation an one liner)

2019-11-10 16:11 UTC, schra commented on tests/radius-search.bats
> +    "lon": 11.00001,
For any test in general, use stable floating point numbers, i.e. numbers that can be represented exactly in memory.

For example, instead of 11.00001 you could use 11.25

2019-11-10 16:11 UTC, schra commented on tests/framework.bash
> +  diff <(echo "$jsonObject" | jq -r "$jqQuery") <(echo "$expectedValue") || (echo "JSON field differs: \`$jqQuery\`. See the diff above." && false)
I propose to do it the following way instead because first printing "JSON field differs" makes more sense than printing it afterwards:

```
@@ -74,7 +74,13 @@ field-equals() {
   local jsonObject=$1
   local jqQuery=$2
   local expectedValue=$3
-  diff <(echo "$jsonObject" | jq -r "$jqQuery") <(echo "$expectedValue")
+
+  local result
+  if ! result=$(diff <(echo "$jsonObject" | jq -r "$jqQuery") <(echo "$expectedValue")); then
+    echo "JSON field \`$jqQuery\` differs:"
+    echo "$result"
+    return 1
+  fi
 }
```

2019-11-12 13:36 UTC, aticu commented on tests/add-facility.bats
> +  field-equals "$result" .result "success"
I think it more clearly reflects the fact, that we're dealing with a literal value there.

2020-01-06 17:50 UTC, schra approved these changes

2020-01-06 17:51 UTC, merged