Remove ripgrep dependency
tonari/backend pull request #6
Opened 2020-01-11 18:20 UTC by aticu

Removes the unnecessary `ripgrep` dependency for tests

2020-01-13 19:39 UTC, schra requested changes
Doesn't work for me:

```
$ cat test
A
A Warning: asdf
Warning: asdf
Error: asdf
thread 'asdf::asdf' panicked at asdfasdf
B
$ cat test | rg "^Error:|^Warning:|^thread '.*' panicked at"
Warning: asdf
Error: asdf
thread 'asdf::asdf' panicked at asdfasdf
$ cat test | grep "^Error:|^Warning:|^thread '.*' panicked at"
$ cat test | grep -E "^Error:|^Warning:|^thread '.*' panicked at"
Warning: asdf
Error: asdf
thread 'asdf::asdf' panicked at asdfasdf
```

I think you have to use `-E` but maybe there is another better flag for this task.

2020-01-14 09:50 UTC, aticu commented
You're right, I forgot about that. Fixed it now.

Should we maybe create a follow-up PR where we check if errors/warning occurred in the `setup` and `teardown` functions of tests? That would be a more general solution.

2020-01-15 13:38 UTC, schra approved these changes

2020-01-15 13:39 UTC, schra commented
I think there was a reason why I only added this check in the radius search initially. If I'm not mistaken there will only be thrown an error/warning/panick if you call certain functions of the API. However, you are probably right, that it wouldn't hurt to check this in any test.

2020-01-15 13:40 UTC, merged